### ISSUE TITLE
Coverage refactoring - Tracking Issue

### ISSUE THREAD

**Issue by Blebowski** [nickg/nvc#880]
Convert all Cover Items to one Bin per item, make each item counter:
1. [x] Branch coverage - Done only half-way, coverage reporting still uses to mask and flag.
2. [x] FSM coverage - Each bin single item, but mask is used
3. [x] Toggle coverage - Not done
4. [x] Expression coverage - Not done

Fully encode bin name into the cover item hierarchy:
1. [x] FSM coverage
2. [x] Toggle coverage
3. [x] Branch coverage
4. [x] Expression coverage

Other internal refactoring / improvements:
1. [x] Saturate run-time counters to avoid overflow and therefore rarily marking covered item as uncovered.
2. [x] Convert unreachability mask to a single bit flag. Since single cover item is single bin, no "unreachability mask" is needed.
3. [x] Convert exclude mask to single bit flag. The same as above

Changes related to the "user":
1. [x] Change specification of exclude files not to require bin name separately -> Since bin name will be part of hierarchy, this will simplify exclude file, its loading, checking and handling.

**Comment by nickg** [comment]
> Make run-time counters 64 bit (32 bit toggle can overflow in realistically long simulation)

This will also double the memory usage of the counters and isn't needed in 99% of cases. It would be better to just make the counter saturate at 2^32 - 1 instead.

**Comment by Blebowski** [comment]
> This will also double the memory usage of the counters and isn't needed in 99% of cases. It would be better to just make the counter saturate at 2^32 - 1 instead.

Agreed. Any solution that does not overflow and will cause covered item to be reported as uncovered in works for me.

**Comment by nickg** [comment]
> It would be better to just make the counter saturate at 2^32 - 1 instead.

I did this in 1745c08.

**Comment by Blebowski** [comment]
Thanks, I have rebased my new branch where I am trying to the the coverage refactoring more gradually. It is still WIP, but I am on a much better track now :) Time wise, I am still busy, but I will try to push it a little.
